title: Mario Sebastian Miklošević
#permalink: https://github.com/ChadHadMad/Portfolio
#logo:
description: Student sam Informatike na <a href=https://www.inf.uniri.hr>  FIDIT-u </a>, završio stručnu spremu za tehničara za računalstvo u <a href=https://ss-elektrotehnicka-ri.skole.hr>SŠER</a>
#show_downloads: true
theme: jekyll-theme-minimal
